version: "3.8"

services:
  # Legacy Python Flask API (can be removed after migration)
  # web:
  #   build: .
  #   command: gunicorn -w 4 -b 0.0.0.0:5001 app:app
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - FLASK_ENV=${FLASK_ENV}
  #     - DATABASE_URL=${DATABASE_URL}

  # New C# .NET 8 Web API
  api:
    build:
      context: ./HTC.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=htc_studio
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api

volumes:
  mongodb_data:
